Extending smoke test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -40,6 +40,8 @@ jobs:
         uses: actions/checkout@v3
       - name: Set up Java
         uses: actions/setup-java@v3
+      - name: Install jq
+        run: sudo apt-get install -y jq
         with:
           distribution: 'zulu'
           java-version: '16'
@@ -49,4 +51,20 @@ jobs:
         run: |
           cd bootcamp-initialisation
           ./buildCliTool.sh
-          ./bootcamp-initialize --git-token=$GIT_TOKEN --org=coreeng --modules=p2p-fast-feedback --bootcampee-repo=bootcamp-initialisation-smoke-test
+          output=$(./bootcamp-initialize --git-token=$GIT_TOKEN --org=coreeng --modules=p2p-fast-feedback --bootcampee-repo=bootcamp-initialisation-smoke-test)
+          
+          github_link=$(echo "$output" | grep -o "https://github.com/[[:alnum:]_-]*/[[:alnum:]_-]*/issues/")
+          echo "Github link: $github_link"
+          
+          repository=$(echo "$github_link" | awk -F'/' '{print $4 "/" $5}')
+          echo "Repository: $repository"
+          
+          issues_count=$(curl -s -H "Authorization: Bearer $GIT_TOKEN" "https://api.github.com/repos/$repository/issues?state=all" | jq length)
+          echo "Number of issues: $issues_count"
+          
+          if [[ $issues_count -ne 4 ]]; then
+            echo "Failed: Number of issues is not equal to 4"
+            exit 1
+          fi
+          
+          echo "Expected number of issues: 4, got: $issues_count"
